### ISSUE TITLE
chat messages can be duplicated

### ISSUE THREAD

**Issue by henryoswald** [sharelatex/web-sharelatex#109]
"I am not sure how to recreate the bug, but I have recently noticed that chats get duplicated. So far, they have only occurred when there were two messages from the same person. Then, those two messages were duplicated. This bug has occurred with myself and two of my collaborators, but not frequently."

**Comment by zeigerpuppy** [comment]
I've seen this too, I'll keep an eye out for it and see if I can reproduce it
