### ISSUE TITLE
should be able to toggle between code and pdf window

### ISSUE THREAD

**Issue by henryoswald** [sharelatex/web-sharelatex#113]
We should add a keyboard shortcut to toggle between the two views: PDF and LaTeX. Currently the user is forced to switch to the mouse to access the PDF view from the LaTeX view and vice versa. This is a very frequent operation and so a keyboard shortcut for the same will make life much easier.

**Comment by pooyahub** [comment]
anxiously waiting for this keyboard shortcut!

**Comment by Tejpbit** [comment]
Any update on this?

**Comment by pooyahub** [comment]
I understand that your question is not directed at me, but here's what I've
done about it.  I have moved on from sharelatex to using latex on my own
computer through emacs, tex live, and auctex.  Sharelatex is nice and neat,
but like all online tools is never as fast as a system installed on your
computer.  Plus, emacs and its packages are designed to do everything
without keyboard with minimal mouse use.  You can also define your own key
bindings in emacs.  For instance, you can do fast editing by importing vi
key bindings to emacs through emacs evil-mode.

**Comment by proximacent** [comment]
@pooyahub Because of one missing shortcut you've gone back to the stone ages?? o_O

**Comment by pooyahub** [comment]
Emacs last release was on December 17, 2016.  That's no ancient time to me.
  I also won't call a 2017 Toyota Camery, a Stone Age vehicle just because
its first release was three decades ago.  I was trying to help, by the way,
by pointing others to what has worked best for me.

**Comment by sn1p3r46** [comment]
+1

**Comment by sn1p3r46** [comment]
Solved?

**Comment by jpallen** [comment]
No, sorry, but I'm trying to tidy up our issues, and this one is part of a bigger problem of the UX of the full-screen PDF mode not being very good, so it's unlikely that we'll address it as a single issue, sorry.

**Comment by rodia216** [comment]
For me Ctrl+Space works. Hope works for you too.

**Comment by Mechandrius** [comment]
Good idea. Im using it on my laptop. Left side is browser/etc. Right side is Latex. Since I only have 0.5 of my screen for Latex, I need to switch alot between code and pdf view. Please introduce a shortcut, that will minimize/maximize the pdf view.

**Comment by sgbaird** [comment]
This is marked as closed. Does this mean pursuing this functionality has been abandoned?
