### ISSUE TITLE
Show a structural overview of the project

### ISSUE THREAD

**Issue by jpallen** [sharelatex/web-sharelatex#12]
Many tex editors display an overview of the document with chapters, sections, subsections, figures, equations etc all displayed in an expanding and collapsing tree. Clicking on an entry should jump to the corresponding file and place.

**Comment by homo-loquens** [comment]
Look forward to seeing this feature implemented. 

In a related note, folding could be improved too. It's now possible to fold paragraphs, and it works beautifully. Implementing the similar thing for the subsections, sections and also preamble would be very useful.

**Comment by zeigerpuppy** [comment]
+1 this is essential for longer documents
