### ISSUE TITLE
ShareLaTeX with a CAS

### ISSUE THREAD

**Issue by ggutzwiller** [sharelatex/web-sharelatex#122]
Hi,

I'm trying to make ShareLaTeX working with a CAS. I read issue #39 but it seems that there's no possibility to use a CAS with ShareLaTeX. 
Do you think there's a solution without having to use unsafe tricks ? I thought of using Apache with ShareLaTeX (issue 83 from sharelatex/sharelatex) or using a Shibboleth module for NginX. 

Did someone succeed to make ShareLaTeX work with a CAS ? 

Sorry for the inconvenience, have a good day.

**Comment by henryoswald** [comment]
Hopefully one day we will get around to re writing the login system, it is part of our road map to add CAS. I will close this issue as we have it mentioned in a few places.
