### ISSUE TITLE
Scroll on large images

### ISSUE THREAD

**Issue by metbosch** [sharelatex/web-sharelatex#124]
When you upload a large vertical image the right scroll don't appear. This issue causes that download button doesn't appear. Moreover, only the upper image part can be seen.
![captura de pantalla 2014-12-10 15 08 29](https://cloud.githubusercontent.com/assets/4162025/5377120/89a37fe6-807e-11e4-9805-c19ddb1781a9.png)

**Comment by jpallen** [comment]
Fixed in #140
