### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by jpallen** [sharelatex/web-sharelatex#13]
ShareLaTeX has not been tested on tablets. We've had reports of various devices working or failing, but not looked into it much. I suspect there will be many quick wins if someone can look into this and test the editor on a tablet.

**Comment by sampsyo** [comment]
For what it's worth, the text editor is also unusable on iOS (see the two issues above). This Ace issue might be relevant: https://github.com/ajaxorg/ace/issues/37

**Comment by henryoswald** [comment]
Thanks that is the big massive Ace thread we will keep an eye on.

**Comment by jrk** [comment]
A major improvement for iOS landed recently: https://github.com/ajaxorg/ace/pull/3310

**Comment by anoteng** [comment]
Bug #312 was closed with reference to this bug. Now this bug is closed, but #312 is still a problem.

**Comment by ildodo12** [comment]
Totally agree, #312  is still a big problem and makes sharelatex basically unusable on a tablet. Which, given that tablets have now wireless keyboards, is truly a shame becuase it would be sooo nice to work on the tablet if you only have that on hands...

**Comment by jrk** [comment]
…not just if it’s the only thing you have on hand. Writing on an iPad with a Smart Keyboard or similar is just a wonderful experience in its own right, *even if you have a laptop or desktop available*. It’s by far my preferred long-form writing tool, and missing sharelatex support is the biggest hole in that.

**Comment by gvita** [comment]
Landed here after having this issue on iPad Pro with external keyboard.
I was pushing my collaborators to sharelatex so that when traveling for conferences we could bring just our iPad Pro's with external keyboard and collaborating on LaTeX projects without having to bring our laptops. However, with this bug, sharelatex is useless for us.

**Comment by gustavnygren** [comment]
I use an iPad pro 10.5, with apples smart keyboard, and sharelatex does not work efficiently; the arrow-keys are non responsive in the text editor, touch-movement is laggy, it is not possible to resize the windows, and I’v experianced (when not using the smartkeyboard) that the editor would jump back where I was previously typing after having change position (with touch).

I would like to help as much as I can to get sharelatex to work for ios, but am afraid I know little about these things. Let me know if I can be of any help.

**Comment by jacobian1128** [comment]
Still unresolved in June 2019.
