### ISSUE TITLE
PDF button in file tree when in fullscreen mode

### ISSUE THREAD

**Issue by max-maag** [sharelatex/web-sharelatex#131]
**Steps to reproduce**:
* Open any LaTeX file in the editor
* Click the "Fullscreen" button in the PDF view if you're not already in fullscreen mode
* Open the file tree if it's not already open

**Problem:**
The button to toggle between the editor and the pdf view is now located in the file tree. Closing the file tree puts the button into the toolbar. After opening the file tree again the button moves to the file tree.

**Expected:**
The button should always be displayed in the toolbar when in fullscreen mode.

**Comment by henryoswald** [comment]
Thanks but we prefer to keep it in the file tree, moving it to the tool bar is a last case resort.
