### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by flop25** [sharelatex/web-sharelatex#132]
Hi
since the new design (red etc) I can't login
I have 404 errors on jquery and angular file on client side, and on server side ERROR no fingerprint for /minjs/libs.js
I really don't know if i have to put them myself to fix it or ....
I hope I posted in the rigth repo

**Comment by jpallen** [comment]
Is this locally or on www.sharelatex.com?

**Comment by flop25** [comment]
locally Hmm maybe I should have posted there : https://github.com/sharelatex/sharelatex ?

**Comment by jpallen** [comment]
Here is fine. Have you run `grunt compile:client` (or better, `grunt install`) in the web directory since updating? You'll need to recompile our coffeescript and less files to js and css.

**Comment by flop25** [comment]
never did this... a "grunt install" didn't change anything

thx a lot for the very quick answers and your job guys
hs: I've just used your contact form about your "server pro" offer

**Comment by flop25** [comment]
did a global update with node.js etc and run again grunt update then grunt install but still same issue
grunt compile:client gives "Warning: Task "compile:client" not found"

**Comment by henryoswald** [comment]
you have to run grunt compile:client from the sharelatex/web directory
