### ISSUE TITLE
Email confirmation

### ISSUE THREAD

**Issue by msimonin** [sharelatex/web-sharelatex#136]
Hi, 

Does Sharelatex support email confirmation  : the user need to confirm  his email adress (for instance using a confirmation link) to finish the registration process.

**Comment by henryoswald** [comment]
It used to but does not any more. Hopefully we will not need it in the future but having the option would be good.

**Comment by msimonin** [comment]
Actually I'm thinking about adding the option. 

Here is my initial idea : 
* In the method ```registerNewUser``` of ```UserRegistrationHandler.coffee``` we change the email sent to add a confirmation link embedding a confirmation token. We flag the user as unconfirmed in the db and store to confirmation token. If email validation option isn't enabled, we just flag the user as confirmed.
* Add a route ```/confirm?email=xxx&token=xxx```
which validates the user (put the confirm flag to true)
* For all operations that requires the user to be authenticated we check the confirm flag as well. We patch the ```SecurityManager.requiresLogin``` method this purpose.

**Comment by msimonin** [comment]
Since it has been referenced in #148 I'll propose a PR for that.
