### ISSUE TITLE
Can't open project

### ISSUE THREAD

**Issue by mconsoir** [sharelatex/web-sharelatex#139]
Hi,
i've got the following error...

Warning: missing space before text for line 58 of jade file "/var/www/sharelatex/web/app/views/project/editor/left-menu.jade"
{"name":"web-sharelatex","hostname":"ifftex","pid":10041,"level":30,"req":{"url":"/project/54ba899616d760c51b353db6","method":"GET","remote-addr":"127.0.0.1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.17 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.17"},"res":{"statusCode":200},"response-time":1317,"msg":"http request","time":"2015-01-17T18:05:25.184Z","v":0}

I didn't change the original code. The installation went fine. I registered a new user and started an example project. In the middle of loading project the server keeps busy. In the log file I found the message above. Is there a quick solution for my problem?

With best wishes,
Markus

**Comment by henryoswald** [comment]
Do you have any errors in your javascript console?
