### ISSUE TITLE
Hijack account for private editing

### ISSUE THREAD

**Issue by 317070** [sharelatex/web-sharelatex#148]
Say user A has a document which he wants to edit privately with user B.
User B has no sharelatex account yet, but user A can add him with the share interface. He only needs to add his mail address.
User A then mails user B to tell him about the repository and that they can co-operate online.
Attacker C creates an account with B's mail address before B does, and can access the private document. There is no verification whether user C actually controls the mail address.

It might be beneficial to enforce mail verification before allowing users to access privately shared documents? (See also #136)

**Comment by jpallen** [comment]
I think the solution to this is to share projects with email addresses with a unique token in the URL. I.e. if I share a project with user B, we create a holding account for them, with a unique token, and then email out the link to the project with that unique token attached. So regardless of what email they eventually sign up with, they get access to that project, and we guarantee that only the recipient of the original share email can access the project.

How does that sound? Thoughts and comments welcome. This is an important part of the UX and security of ShareLaTeX, so we should make sure we get it right!

**Comment by 317070** [comment]
It does sound like a good solution.

But I wonder if it would be possible to invite people to work on a common project besides mailing them. I for one like the slack we use at our lab.

Wouldn't it be possible to create a one-time-only-invite-url for instance?

**Comment by jpallen** [comment]
Yes, one-time-only-invite-url was essentially what I had in mind. If you invite someone by email we'll send that URL to their email address, but I suppose there's no reason we couldn't give it to you to share manually as well.

**Comment by henryoswald** [comment]
we have a one time token handler which was recycled from the password reset process that would work well for this - https://github.com/sharelatex/web-sharelatex/commit/fe30571893e512916d702ea246372b195050ca1a
