### ISSUE TITLE
vim keybindings, let ':w' recompile

### ISSUE THREAD

**Issue by moretea** [sharelatex/web-sharelatex#152]
On my local machine, I usually run a program which recompiles any .tex files as soon as they are saved. 

Could you bind the save function of the ACE editor to the recompile button? This saves time by making the keyboard-to-mouse-and-back steps superfluous.

**Comment by jpallen** [comment]
Thanks for the suggestion. It's not the same shortcut, but you should be able to do this with Ctrl+Enter at the moment. I doubt we will override :w since that seems a little confusing since it's not really 'saving' as one would expect, sorry.

**Comment by willhaines** [comment]
I too would love this functionality. Is there any way to personally map functions within the editor?

**Comment by abjugard** [comment]
I would like this functionality as well.

**Comment by apokellypse** [comment]
I would love to have a way to map functions within the editor.

**Comment by abjugard** [comment]
Any chance you'll consider implementing this? :w does nothing otherwise so it would be a perfect function to be honest.
