### ISSUE TITLE
Unable to Open Project

### ISSUE THREAD

**Issue by ChunyangD** [sharelatex/web-sharelatex#153]
For some reason, the online ShareLaTeX refuses to open any project for me. While I can access the list of projects, it gets stuck at the loading screen with the lion. I am currently using Windows 8.1 and Google Chrome. 

I opened up the JavaScript console and found this message:

WebSocket connection to 'wss://www.sharelatex.com/socket.io/1/websocket/WskPuIqRHVCfGmYmVs15' failed: WebSocket is closed before the connection is established

Can anyone advise on next steps?

**Comment by henryoswald** [comment]
Do you have a bit of software called superfish installed?
Do you have the real time sharelatex process running?

On Fri, Feb 20, 2015 at 5:30 PM, Chunyang Ding <notifications@github.com>
wrote:

> For some reason, the online ShareLaTeX refuses to open any project for me.
> While I can access the list of projects, it gets stuck at the loading
> screen with the lion. I am currently using Windows 8.1 and Google Chrome.
>
> I opened up the JavaScript console and found this message:
>
> WebSocket connection to 'wss://
> www.sharelatex.com/socket.io/1/websocket/WskPuIqRHVCfGmYmVs15' failed:
> WebSocket is closed before the connection is established
>
> Can anyone advise on next steps?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/153>.
>



-- 
Henry Oswald
shareLaTeX.com creator

**Comment by ChunyangD** [comment]
I'm running Malwarebytes right now to detect for Superfish. I'm not sure what Real Time Sharelatex Process is.

**Comment by henryoswald** [comment]
You also need to run an instance of this -
https://github.com/sharelatex/real-time-sharelatex

On Fri, Feb 20, 2015 at 5:53 PM, Chunyang Ding <notifications@github.com>
wrote:

> I'm running Malwarebytes right now to detect for Superfish. I'm not sure
> what Real Time Sharelatex Process is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/153#issuecomment-75286945>
> .
>



-- 
Henry Oswald
shareLaTeX.com creator

**Comment by ChunyangD** [comment]
Issue closed. Confirmed - Superfish was running as malware in the background that Windows Defender did not detect. A sweep of Malwarebytes eliminated the problem and files are opening properly. Many thanks.
