### ISSUE TITLE
Custom vimrc file

### ISSUE THREAD

**Issue by aVolpe** [sharelatex/web-sharelatex#155]
The `ace` editor that come with sharelatex works great, but I always (when open the page) use this commands:

```
:imap j gj
:imap jj <Esc>
:imap k gk
```

And other common vim maps, is possible to have something like a `vimrc` in sharelatex?

I know the subset of operations that `ace` support is very limited, but the map thing work great and is a nice feature.

**Comment by jpallen** [comment]
Interesting, I wasn't aware that Ace even supported remapping of keys! This definitely makes have a custom .vimrc file a compelling idea. It will likely be a while before we get a chance to look at this (if we do), but I'll leave this issue open for comments and suggestions in the mean-time.

**Comment by rehanog** [comment]
Agree. This would be great.

**Comment by bluddy** [comment]
I would love to have this supported as well.

**Comment by natema** [comment]
IMHO, what Sharelatex really lacks to make it the definitive editor for Vim users is support for Vim Latex Suite plugin.

**Comment by johannesburg** [comment]
Can confirm--using the vim emulator without a jk -> esc is a little painful.

**Comment by timediv** [comment]
Is this still planned to be implemented?

**Comment by henryoswald** [comment]
one day maybe, unlikely to happen any time soon.

**Comment by llinfeng** [comment]
Linking the "official" solution: [How can I define custom Vim macros in a vimrc file on Overleaf? - Overleaf, Online LaTeX Editor](https://www.overleaf.com/learn/how-to/How_can_I_define_custom_Vim_macros_in_a_vimrc_file_on_Overleaf%3F).

The demo code demonstrated the standard mappings under various mode.
```
imap jj <ESC>
" vimKeyboard.Vim.map("jj", "<Esc>", "insert")
nmap h j
" vimKeyboard.Vim.map("h", "j", "normal")
```

However, a much-needed mapping is missing from the demo: to trigger the following element on the Overleaf web-interface for **forward search**. I will reply under this post if I shall map such action to `<localleader>lv`, as in [`vimtex`](https://github.com/lervag/vimtex/blob/52d49ceed060a41e66046bfa7576d41cbf67d6fd/doc/vimtex.txt#L3990). 
![image](https://user-images.githubusercontent.com/5890407/79008681-e3919300-7b2b-11ea-83e7-4b2c8eae196b.png)

**Comment by llinfeng** [comment]
For those who are interested in "sourcing your beloved `.vimrc` on Overleaf", please refer to the following TamperMonkey Script:
* [Overleaf_V2_mappings](https://gist.github.com/llinfeng/8e003b2107d7ab25e5daedc27c5730ae)

Full Credits to Harutyun Amirjanyan for the jump-to-PDF script, as found on the [Ace forum, in this post](https://groups.google.com/d/msg/ace-discuss/gwXMzUM17I4/W2pWhBSbAAAJ).

**Comment by ugirc** [comment]
You can simply add following code in TamperMonkey Script to remap vim keys like .vimrc.
```html
// ==UserScript==
// @name         Overleaf Editor Custom VIM Keybindings
// @namespace    http://tampermonkey.net/
// @version      0.1
// @match        https://www.overleaf.com/project/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    // poll until editor is loaded
    const retry = setInterval(() => {
        if (window._debug_editors === undefined) return
        clearInterval(retry)
        // get current editor instance
        const editor = window._debug_editors[window._debug_editors.length -1]
        // vim keyboard plugin
        const vimKeyboard = window.ace.require("ace/keyboard/vim")
        // add custom keybindings - insert mode applies on insert
        vimKeyboard.Vim.map("a;", "<Esc>", "insert")
        vimKeyboard.Vim.map("a;", "<Esc>", "visual")
        // normal mode applies while escaped
        vimKeyboard.Vim.map("H", "^", "normal")
        vimKeyboard.Vim.map("L", "$", "normal")
        vimKeyboard.Vim.map("[", "{", "normal")
        vimKeyboard.Vim.map("]", "}", "normal")
        vimKeyboard.Vim.map("j", "gj", "normal")
        vimKeyboard.Vim.map("k", "gk", "normal")
        vimKeyboard.Vim.map("J", "5gj", "normal")
        vimKeyboard.Vim.map("K", "5gk", "normal")
        // set the modified keyboard handler for editor
        editor.setKeyboardHandler(vimKeyboard.handler)
        console.log("Custom key bindings applied")
    }, 100)
})();
```
