### ISSUE TITLE
Project title editability issues

### ISSUE THREAD

**Issue by applixy** [sharelatex/web-sharelatex#171]
1. If a project is publicly writable, the project title cannot be changed by a public editor.
2. Even for a read only project, the UI for changing the project title is available to the public. However, the project title change submission won't be successful.

1 is caused by a misplaced order of authentication checking in 
`app/coffee/managers/SecurityManager.coffee`
`userCanModifyProject`

2. is caused by the misconfiguration of  `ng-show` of the `projectNameController` in file
`app/views/project/editor/header.jade`

**Comment by henryoswald** [comment]
thanks, fixed with:
https://github.com/sharelatex/web-sharelatex/commit/014ea5ee7efe6161e7dc4a32510323a7ca5e22c0
