### ISSUE TITLE
Please don't remove the public registration feature

### ISSUE THREAD

**Issue by oxan** [sharelatex/web-sharelatex#175]
There are people who actually want and use public registration of accounts, and protect the installation by other means (such as HTTP authentication and/or firewalling). I'm not going to create an account for everyone that wants to use our ShareLaTeX installation. At least implement something like RADIUS or LDAP authentication before completely removing the ability for users to create their own accounts.

This makes upgrading to v0.1.4 unacceptable for us.

**Comment by henryoswald** [comment]
sorry but we have decided to go this path as it seems to make most people happy and keeps the code simple. We do have public/ldap/etc available as part of ShareLaTeX server pro.

**Comment by oxan** [comment]
Removing a feature from an open source project and then redirecting them to a closed-source paid version to get the same feature back is in poor taste in my opinion. I'll be working on a free alternative implementation of this feature.

**Comment by henryoswald** [comment]
Hi oxan,

it is not our intention todo a bait and switch, but we do have to make decisions which we think are for the best for the software & community and this is one of them sorry. We have not removed any of the public registration code from the git history so it is all there if you want to maintain a fork.
