### ISSUE TITLE
Existing project while in pdf full-screen removes pdf viewer

### ISSUE THREAD

**Issue by applixy** [sharelatex/web-sharelatex#179]
Bug description:
If a user exists a project while the pdf full-screen mode is on, and then enters any projects, the project will display the ace editor in full screen without the pdf viewer at all. The user has to click the "PDF" button on the header in order to get the pdf viewer back.
It gets worse: if the user exits a project where the left-most panel (file browser) is on and the pdf viewer is in full-screen mode, upon re-entering any project, no pdf viewer will be displayed, and the "PDF" button on the header is also missing. This means that the user will not be able to get the pdf viewer back, unless they first turns off the left-most panel to get the "PDF" button on the header to re-appear.

Expected behaviour:
A user should be able to re-enter a project with the exact same configuration as when they left the project. If the project was in pdf full-screen mode, re-entry should show the user pdf full-screen mode instead of the editor full-screen mode.

Steps to reproduce the bug:
1. start a project
2. enable the left-most panel by clicking the left-most ">" button
3. click the "full screen" button on the pdf viewer
4. exit the project to the list of project page
5. re-enter the project.

**Comment by Hejamy** [comment]
I've also experience the events described above.

**Comment by BrainDoctor** [comment]
I can confirm this bug.

**Comment by Fubble** [comment]
I have also experienced this bug.

**Comment by mqg** [comment]
still experiencing this bug. Especially this part "If a user exists a project while the pdf full-screen mode is on, and then enters any projects, the project will display the ace editor in full screen without the pdf viewer at all."
It should be more obvious how to get the pdf preview back to the right half of the screen.

**Comment by henryoswald** [comment]
Can someone share a screen shot please.

sent from my phone.

**Comment by kevindehecker** [comment]
![image](https://cloud.githubusercontent.com/assets/5213220/13965339/3027e644-f06e-11e5-883b-1afb046cd3d5.png)

**Comment by Houda-Lam** [comment]
here is a fix for that issue with snapshots:
http://sharelatex.tenderapp.com/help/kb/latex-editor/lost-split-screen
hope it will work for you

**Comment by erikrtn** [comment]
Thanks but split-screen view button and the rightmost side-bar should not disappear like that :(

**Comment by krilar** [comment]
Experienced this bug today, could not figure out how to get the split-screen back. This page helped me, thanks :)

Please move the "split screen" button from the PDF-viewer to always be visible even when in text editing mode. Having to move from the document you are inside and go to the PDF and then clicking "split screen" to return to the regular view is very awkward and not intuitive from where the buttons are normally placed.

**Comment by oanatoco** [comment]
Very helpful - especially since I couldn't find a fix on their support page (the link posted above to sharelatex.tenderapp doesn't go to a specific thread)

So thanks!

(Also, why is this still a bug, ShareLaTeX???)

**Comment by DanlanChen** [comment]
not working

**Comment by chrisgramberg678** [comment]
Hi, I experienced this issue today. The problem is not that the viewer is minimized. The bar on the right hand side is not there. I've attached a screenshot for your reference.
<img width="1440" alt="screen shot 2017-08-05 at 9 20 40 pm" src="https://user-images.githubusercontent.com/3665243/29000559-206560d8-7a24-11e7-9d82-5423b72079e2.png">

**Comment by DanRunfola** [comment]
This appears to still be at issue today; I just had this exact issue come up.

**Comment by OwenOLevin** [comment]
This issue still seems to exist...

**Comment by MarcoKull** [comment]
Same issue here.
