### ISSUE TITLE
Problems creating admin user

### ISSUE THREAD

**Issue by sigurdtheone** [sharelatex/web-sharelatex#182]
I am having some problems with the final step to setting up a production environment.

The website runs as expected, however I am not able to create the admin user for the site.

Running the command "grunt create-admin-user --email mymail@mydomain" produces the following output:

>$ sudo grunt create-admin-user --email mymail@mydomain
>Warning: Task "create-admin-user" not found. Use --force to continue.

>Aborted due to warnings.

Running a command like grunt check:aspell works fine:

>$ sudo grunt check:aspell
>Running "check:aspell" task
>Checking aspell is installed... OK.
>The following spell check dictionaries are available:
>en
>en-variant_0
>en-variant_1
>....

Currently i have no leads on a next step, and i cannot gain access to the site itself without the admin user. Next step would be to scrap the server and start over.

Will appreciate any suggestions :)

**Comment by jpallen** [comment]
Are you in the base sharelatex repository? And is it up to date with the latest release branch?

**Comment by sigurdtheone** [comment]
Yep - Currently sitting in /var/www/sharelatex/

I copied the sharelatex files Tuesday of this week using the following command:
sudo git clone -b release https://github.com/sharelatex/sharelatex.git /var/www/sharelatex

Current available tasks for grunt are:
http://pastebin.com/HUNnGU95

**Comment by jpallen** [comment]
Ah sorry, my bad, you need to be in the 'web' directory for it to work (it's in the web Gruntfile).
