### ISSUE TITLE
Collaborator is redirected to register page instead log in page when a project is shared

### ISSUE THREAD

**Issue by msimonin** [sharelatex/web-sharelatex#185]
## Scenario 

User A is registered to sharelatex and owns project A
User B is registered to sharelatex

User A shares project A with User B. 
User B received a notification email with the following link to follow : 
```http://sharelatex.local/project/54be70a52dffae5e606c9361?project_name=projectA&user_first_name=userA@domain.com&new_email=userB@domain.com&r=5620df74&rs=ci ```

## Observed behaviour 

User B click on the link and is redirected to register page.

NB : this has been observed on my local installation (v0.1.4) and on sharelatex.com

## Expected behaviour

User B click on the link and is redirected to login page.

## Ideas 

In ```AuthenticationController.coffee``` a test is made to check whether to redirect to register page or log in page. 

```coffee
_redirectToLoginOrRegisterPage: (req, res)->
  if req.query.zipUrl? or req.query.project_name?
    return AuthenticationController._redirectToRegisterPage(req, res)
  else
    AuthenticationController._redirectToLoginPage(req, res)
```

We fall in the first case due to the ```project_name=projectA``` in the link.

I can PR it if needed but don't know what is the best way to fix it:
 
* Change the test in ```req.query.project_name?``` in the above method (what will be the side effect ?)
* Change the email template to remove (at least) ```project_name=projectA``` (do we need the whole query string ?)
* Or ?

**Comment by henryoswald** [comment]
Hey

you can actually login with the registration form, I think the answer is probably to make that behaviour clear rather than adding more complexity to the redirects for logins.

**Comment by msimonin** [comment]
Got it :) 
But landing on a page whose title is "register" is a little bit confusing.
