### ISSUE TITLE
Can't compile projects (Error: "name" and "value" are required for setHeader)

### ISSUE THREAD

**Issue by dpasqualin** [sharelatex/web-sharelatex#186]
Hi, when I load a project I get several errors, the pdf preview in the browser shows this:
```
Server Error Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.
``` 

The error below appears on the server, and sharelatex-web app dies(!):
```
Exception: Error: "name" and "value" are required for setHeader().
  at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
  at new ClientRequest (_http_client.js:101:14)
  at Object.exports.request (http.js:49:10)
  at Request.start (/home/sharelatex/sharelatex/web/node_modules/request/request.js:672:30)
  at Request.write (/home/sharelatex/sharelatex/web/node_modules/request/request.js:1314:28)
  at /home/sharelatex/sharelatex/web/node_modules/request/request.js:408:16
  at process._tickDomainCallback (node.js:381:11)
```
I also get many of this erros on nginx error.log:
```
2015/05/27 16:13:02 [error] 11839#0: *371 connect() failed (111: Connection refused) while connecting to upstream, client: 200.17.202.33, server: _, request: "GET /project/5565cae1f83ff2115679dafd HTTP/1.1", upstream: "http://127.0.0.1:3000/project/5565cae1f83ff2115679dafd", host: "sharelatex.c3sl.ufpr.br", referrer: "http://sharelatex.c3sl.ufpr.br/project"
2015/05/27 16:13:02 [error] 11839#0: *371 connect() failed (111: Connection refused) while connecting to upstream, client: 200.17.202.33, server: _, request: "GET /project/5565cae1f83ff2115679dafd HTTP/1.1", upstream: "http://[::1]:3000/project/5565cae1f83ff2115679dafd", host: "sharelatex.c3sl.ufpr.br", referrer: "http://sharelatex.c3sl.ufpr.br/project"
```

On the console in the browser I see the following (but I'm guessing they appear because sharelatex-web is dead by this time:
```
POST http://sharelatex.c3sl.ufpr.br/project/5565cae1f83ff2115679dafd/compile?auto_compile=true
502 Bad Gateway
POST http://sharelatex.c3sl.ufpr.br/spelling/check
502 Bad Gateway
```

Nginx running as user sharelatex with config:
https://github.com/sharelatex/sharelatex/wiki/Nginx-as-a-Reverse-Proxy

Node v0.12.4, nginx 1.6.2, latexmk 4.39, redis-server 3.0.1

**Comment by henryoswald** [comment]
if you go directly to localhost:whateverport does it work? checkout the tag v0.1.4 it will take you off unstable

**Comment by dpasqualin** [comment]
I tried with tag v0.1.4 and the problem persists.

bcrypt 0.7.5 (in v0.1.4) won't compile with node 0.12, so I updated to 0.8.5.
siteUrl and websocketsUrl are the same in both configs (sharelatex/config and sharelatex/web/config).
behindProxy is true on both configs as well.

Tomorrow morning I'll check on the localhost:3000. If it works, any hint on where the problema might be?

**Comment by henryoswald** [comment]
im not sure right now but using node 0.10 might help

**Comment by dpasqualin** [comment]
I reverted the changes on my config files and tried using localhost:<port> with no success, neither on master branch nor or v0.1.4.

Aftwerwards I deleted all repositories and started from scratch, but this time using node 0.10.38, and it worked perfectly (tried only on master branch).

So, I think it's safe to say that sharelatex doesn't support node 0.12 right now.

**Comment by henryoswald** [comment]
that sounds about right, we are planning on moving to 0.12 this summer

On Thu, May 28, 2015 at 7:17 PM, Diego Giovane Pasqualin <
notifications@github.com> wrote:

> I reverted the changes on my config files and tried using localhost: with
> no success, neither on master branch nor or v0.1.4.
>
> Aftwerwards I deleted all repositories and started from scratch, but this
> time using node 0.10.38, and it worked perfectly (tried only on master
> branch).
>
> So, I think it's safe to say that sharelatex doesn't support node 0.12
> right now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/186#issuecomment-106545614>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by dpasqualin** [comment]
Well, problem solved :)
Closing the issue...
