### ISSUE TITLE
Open PDF preview in seperate window

### ISSUE THREAD

**Issue by budde377** [sharelatex/web-sharelatex#190]
Having the PDF and the code previewed side-by-side is an extremely useful feature! Extending this feature by enabling preview in a separate window would work better with multi-monitor / -workspace setup. 

Right now this can (sort of) be achieved by opening a new browser window and navigating to sharelatex, but lack cross-preview-code navigation and will view the user as logged-in twice (which can be very annoying).

**Comment by jpambrun** [comment]
Came here to ask the same thing. Also, with the workaround, the preview is not updated when compiling from the "code window".

**Comment by tunfastdev** [comment]
@budde377  @jpambrun 
Hi, I found a simple solution , open your project in two tabs (or windows), in the first one hide the preview and in the second on hide the code.When you make change in the code of the first tab Sharelatex will automatically updates the second tab code and you can recompile the preview with the new added code.
There might be a small delay in the updates between the two tabs.
I hope this will answer your question.

**Comment by MauritsDK** [comment]
@tunfastdev 
Came here for the same question great solution, only it makes me feel abit stupid

**Comment by wywzxxz** [comment]
not working... is auto-compile a feature for the pro edition ?

**Comment by joaomlneto** [comment]
> not working... is auto-compile a feature for the pro edition ?

I don't think so -- you still have to click to recompile

**Comment by ermisp** [comment]
This would be a pretty nice feature! I actually use local editors and only use sharelatex to synchronize with others... If this feature was available i would only use sharelatex and it would be great!!!

**Comment by joaomlneto** [comment]
I assume it's closed because of the merge with Overleaf, which already has this feature?

**Comment by jpallen** [comment]
Sorry, no, I should have said, I'm just trying to tidying some of these issues, and this one isn't on our roadmap at the moment due to the complexity it would introduce, both from a code and UX perspective.

**Comment by eric-wieser** [comment]
Note there's [an overleaf blog post from November 2017](https://www.overleaf.com/blog/578-tip-of-the-week-displaying-source-and-preview-on-different-monitors) saying this feature is supported.

Unfortunately, [a FAQ entry](https://www.overleaf.com/learn/how-to/Can_I_view_the_preview_in_a_different_browser_tab_or_window%3F) says it is no longer supported.

**Comment by nbdd0121** [comment]
I don't think there's any complexity in supporting this. Just add a button near the fullscreen button, when it is clicked, use `window.open` to create a new window. You can just manipulate the DOM of the new window.

**Comment by tobiasrenkin** [comment]
any news on this?
