### ISSUE TITLE
Auto compilation doesn't work

### ISSUE THREAD

**Issue by ipsq** [sharelatex/web-sharelatex#193]
I'm using the sharelatex-docker image and when I make a change, the compilation doesn't happen automatically. How do I enable this behaviour? Is it a setting I have to enable somewhere? There are no errors in the console.

**Comment by henryoswald** [comment]
Hi,

auto compile is not available at the moment. Maybe in the future we will
get to it.

On Wed, Jun 24, 2015 at 12:03 PM, Martijn Riemers <notifications@github.com>
wrote:

> I'm using the sharelatex-docker image and when I make a change, the
> compilation doesn't happen automatically. How do I enable this behaviour?
> Is it a setting I have to enable somewhere? There are no errors in the
> console.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/193>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by ipsq** [comment]
Thank you for the quick reply.

**Comment by ipsq** [comment]
Hacky, but it works!

```javascript
var a;
var b = 3000;
editors[0].getSession().on('change', function() {
    clearTimeout(a);
    typingTimer = setTimeout(setInterval(angular.element($('*[ng-controller="PdfController"]').find('a').first()).scope().recompile, b);
});
```

**Comment by henryoswald** [comment]
Thanks, this isn't really very feasible for most people sorry as it would hammer the server. We might do a smarter version in the future.

**Comment by ataiya** [comment]
Out of curiosity, what's the **chance** of sharelatex having a client-heavy solution in the future? 
(that support live updates on save without killing your server)
