### ISSUE TITLE
All paths are absolute, making rebase impossible

### ISSUE THREAD

**Issue by earthquakesan** [sharelatex/web-sharelatex#197]
Running sharelatex under non-root URI is impossible at the moment, because all URIs used in href are absolute (i.e. starts with /). That makes it impossible to run sharelatex under non-root URI, like http://myhost.com/sharelatex

To fix it 

```
1. add to head tag in app/views/layout.jade:
base(href="/")
2. Substitute all absolute URIs to relative (by simply removing slash in front)
# grep -ri "href"
then manually editing files
is there a test suite for the project?
```

Also, it would make sense having base as a variable in docker image for easy deploy. At the moment deployment is only possible under root URI, which is totally understandable, because main project runs at sharelatex.com, however it does not help for dissemination of the project. The usual scenario for deployment in university is when you have to run it under some path (in my case http://informatik.uni-leipzig.de/campus2020/sharelatex), however it is impossible without above mentioned fixes right now.

**Comment by henryoswald** [comment]
thanks, lots of discussion on this here https://github.com/sharelatex/sharelatex/issues/83

will leave this issue open as its more precise.

**Comment by earthquakesan** [comment]
@henryoswald hi Henri! I will make a pull request to fix it, it's quite trivial for me (I've done the similar thing in another web app I'm maintaining). Can you please tell me if there is a test suite for following links (like selenium automated tests or something)?

**Comment by henryoswald** [comment]
Hi, we don't have any acceptance tests for the website sorry.
