### ISSUE TITLE
Bad rendering of some text

### ISSUE THREAD

**Issue by henryoswald** [sharelatex/web-sharelatex#198]
We have started to see some strange rendering on the pages with text, mainly in chrome. Resizing the page always fixes all of these problems. They seem to generally happen when the page is quite narrow.

1) if you load the page https://www.sharelatex.com/about with it selected quite narrowly (less than a 13" macbook monitor) then the email address at the bottom will render badly
<img width="651" alt="2015-09-02 at 11 02" src="https://cloud.githubusercontent.com/assets/343366/9628341/1355b95c-5162-11e5-946b-f622762aa9c4.png">

2) The text will not render some times example on learn home page https://www.sharelatex.com/learn 

<img width="1022" alt="2015-09-02 at 10 54" src="https://cloud.githubusercontent.com/assets/343366/9628151/f57fd08a-5160-11e5-80e2-d306dd22f22a.png">

3) sometimes text does not sit in the box nicely (look at 'This')
<img width="856" alt="2015-09-02 at 10 57" src="https://cloud.githubusercontent.com/assets/343366/9628241/6e7cd7ee-5161-11e5-9eb8-4a9ad37a66cf.png">

4) around where code elements are used the rendering will often overlap  https://www.sharelatex.com/learn/Bibliography_management_with_bibtex (lower down on page)
<img width="536" alt="2015-09-02 at 11 01" src="https://cloud.githubusercontent.com/assets/343366/9628329/ff866570-5161-11e5-9a0b-ada6332685ca.png">

**Comment by acconrad** [comment]
Hi @henryoswald can you assign this to me? I'll take a look at this this week

**Comment by henryoswald** [comment]
I think you have left the team as we have hit github limits so can't assign atm. Let me know if you need anything.

**Comment by acconrad** [comment]
@henryoswald if you could try one thing - change your base font on your local instance from `"Open Sans", sans-serif;` to `Helvetica, Arial, sans-serif;` One issue I've seen in the Chrome forums is that web fonts can cause rendering issues. Another thing I would remove is `text-rendering: optimizeLegibility` and `-moz-osx-font-smoothing: grayscale`, as they mess around with rendering as well. I'm not 100% that this will work, but the common thread over the years with font overlapping/missing anchor tags has to do with custom fonts. See if a stock desktop font (Helvetica for Mac, Arial for Win) doesn't resolve this.
