### ISSUE TITLE
Search path for custom styles and files in subfolders

### ISSUE THREAD

**Issue by Anthony-Gaudino** [sharelatex/web-sharelatex#202]
Users may want to add a custom style and other files to a sub-folder and there is no way to set a search path for subdirectories.

One example is using the `datetime2 package`, there is the `.sty` file and the `.ldf` language files used by this package.
The user want to put all them in a sub-folder called datetime2 but there is no way to set latex to search in that folder.

The user can use `\RequirePackage{datetime2/datetime2, setspace}`, but then it wont load the language files and errors will appear.

**Comment by ambs** [comment]
Gets worse (or equally bad) with beamer themes, that use a bunch of .sty files. And the `\usetheme` command won't accept a path.
