### ISSUE TITLE
Adding custom project template

### ISSUE THREAD

**Issue by msimonin** [sharelatex/web-sharelatex#203]
When creating a project users have a choice between "blank project" or "example project". Is there a way to provide other project templates to the user ?

**Comment by msimonin** [comment]
According to the [ProjectCreationHandle file](https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/Features/Project/ProjectCreationHandler.coffee#L40) it seems that we can't easily create another project templates unless we modify this code and create the required files in a subdirectory of  app/templates/project_files

Creating custom project templates by creating a subdirectory in app/templates/project_files without modifying the code is an interesting feature to me. In that case a list of templates available will maybe have to reside on the config file.

Any thoughts on this ?

**Comment by zeigerpuppy** [comment]
This would be a great feature, a simple way of maintaining a template library would be really useful

**Comment by henryoswald** [comment]
This is something we offer as the premium version of ShareLaTeX so we are not going to add it into the community version.
