### ISSUE TITLE
Keep scroll fix while multiple users are editing

### ISSUE THREAD

**Issue by metbosch** [sharelatex/web-sharelatex#204]
When two users edit the same file and they work in different lines. Every time that the user in the top inserts a new line, the focus of the second editor who is in the bottom part of the file is moved down. This may place the line of the second editor outside of the screen, besides this behaviour is very annoying.

**Comment by zeigerpuppy** [comment]
agreed, this can be difficult to manage when editing close bits of text

**Comment by jpallen** [comment]
This isn't perfect yet, but should be significantly improve from when this issue was opened.
