### ISSUE TITLE
[feature] Paste tables

### ISSUE THREAD

**Issue by dfelder** [sharelatex/web-sharelatex#207]
It should be possible to detect when a table is pasted eg. from Excel and automatically generate the Latex code. This can be a full table/tabular environment or just the & and \\ between values.

**Comment by henryoswald** [comment]
I don't think we will ever want to be that cleaver reading excel data so im going to close for now.

**Comment by dfelder** [comment]
```coffeescript
editor.on "paste", (o) ->
		lines = o.text.split("\n")
		tabs = ((l.match(/\t+/g)||[]).length for l in lines)
		o.text = o.text.replace(/\t/g,"\t& ").replace(/\r?\n/g,"\\\\\n") if \
				lines.length > 3 and 
				tabs.length > 2 and 
				tabs.reduce (a,b) -> if a==b then a else false
```
It's virtually no effort and works for all kinds of tables. If we can think of a scenario where this could cause problems, we could include a check whether the cursor is inside a tabular environment.

**Comment by henryoswald** [comment]
Thanks, maybe one day we will get to this but moving to the point where we
start to get 'smart' with what people insert into the editor is a bit away
at the moment. In our experience these things although trying to help can
just annoy people as the thousands of people who paste into ShareLaTeX.com
every day do find all edge cases.



On Sat, Dec 12, 2015 at 12:00 AM, Daniel Felder <notifications@github.com>
wrote:

> editor.on "paste", (o) ->
>         lines = o.text.split("\n")
>         tabs = ((l.match(/\t+/g)||[]).length for l in lines)
>         o.text = o.text.replace(/\t/g,"\t& ").replace(/\r?\n/g,"\\\\\n") if \
>                 lines.length > 3 and
>                 tabs.length > 2 and
>                 tabs.reduce (a,b) -> if a==b then a else false
>
> It's virtually no effort and works for all kinds of tables. If we can
> think of a scenario where this could cause problems, we could include a
> check whether the cursor is inside a tabular environment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/207#issuecomment-164084536>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder
