### ISSUE TITLE
[bug] wordcount fail

### ISSUE THREAD

**Issue by RGunning** [sharelatex/web-sharelatex#211]
There is a bug in the worcounter.
If the main document is not in the top level of the project folder, it does not count properly (I was getting 0 words 7 headers). Moving the main document to the top level fixes this (it suddenly finds 24532 words 21 headers).

This is easy enough to fix on a per project basis, but many of the templates don't have the main document at the top level of the project tree so will run into this problem.

**Comment by teferra1** [comment]
I have the main document on the top (or I think I have it there) yet  I am getting 1 header and 14 words only.
