### ISSUE TITLE
Can't manage to set up nodemailer for direct transport

### ISSUE THREAD

**Issue by Micket** [sharelatex/web-sharelatex#214]
I have nodemailer installed, tested it manually in node, and I can have it send off an email with direct transport ( using `transport = nodemailer.createTransport()` as shown in the examples on nodemailer.com )

I tried to modify the email options in `/etc/sharelatex/settings.coffee` using
```coffeescript
email:
    fromAddress: "noreply@mysite.com"
    replyTo: "my.name@mysite.com"
    transport: "direct"
```
(also without specifying the `transport:` option altogether). Restart the server and.. nothing. No emails arrive and I can't find no related error messages in the logs either.

If not this, then how is the setup for direct transport supposed to be done?

I am using the docker version, but since the options where there, it seems that it's recent enough to have nodemailer support in already.

**Comment by henryoswald** [comment]
I can't help you too much as we never use direct sorry, checkout which version of nodemailer we use as its quite old and keep fiddling with the options.
