### ISSUE TITLE
Ace editor fails to load

### ISSUE THREAD

**Issue by andrew-bohr** [sharelatex/web-sharelatex#217]
Sometimes (pattern seems random to me) ace editor fails to load given this error in console:
```
[Error] ReferenceError: Can't find variable: ace
	(anonymous function)
[Error] Error: undefined is not an object (evaluating 'ace.require("ace/autocomplete").Autocomplete')
...
```
Reloading page usually resolves the issue. Any suggestions how to fix this? Anyone encountered this bug?

Here is complete console log:
[error.txt](https://github.com/sharelatex/web-sharelatex/files/90418/error.txt)

**Comment by henryoswald** [comment]
Do you have the JS minified?

On Thu, Jan 14, 2016 at 1:10 PM, andrew-bohr <notifications@github.com>
wrote:

> Sometimes (pattern seems random to me) ace editor fails to load given this
> error in console:
>
> [Error] ReferenceError: Can't find variable: ace
>     (anonymous function)
> [Error] Error: undefined is not an object (evaluating 'acerequire("ace/autocomplete")Autocomplete')
>
>
> Reloading page usually resolves the issue Any suggestions how to fix this?
> Anyone encountered this bug?
>
> Here is complete console log:
> errortxt
> <https://githubcom/sharelatex/web-sharelatex/files/90418/errortxt>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/217>.
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by andrew-bohr** [comment]
No, I do not, I have ``useMinifiedJs: false`` in main config file.

**Comment by henryoswald** [comment]
Keeping it minified should fix it.


On Thu, Jan 14, 2016 at 1:26 PM, andrew-bohr <notifications@github.com>
wrote:

> No, I do not, I have useMinifiedJs: false in main config file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/217#issuecomment-171644389>
> .
>



-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by andrew-bohr** [comment]
Thank you! This bug is hunting me for quite some time. I'll post results, when I try your solution.

**Comment by andrew-bohr** [comment]
Bug is nowhere to be seen with JS minified.
