### ISSUE TITLE
Notification of compilation completion

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [sharelatex/web-sharelatex#225]
When editing in ‘full-screen mode’ (i.e., not split-screen mode, and with the file list hidden on the left), there's no indication when re-compilation is complete! It'd be great if there were a little toast notification or something indication when re-compilation has completed, while editing (I tend to multitask, and trigger re-compilation after changing one block, while beginning to work on the next block: I don't like waiting. :P)

(On a similar note, is there a hotkey for triggering re-compilation, so I don't have to jump out of my editing flow *twice* two check how it looks [once to trigger, back to editing, then again to check the results]? Specifically, in vim-mode?)

**Comment by jpallen** [comment]
You can use Ctrl/Cmd+Enter to trigger a recompile
