### ISSUE TITLE
PDF is downloaded, not shown in Browser

### ISSUE THREAD

**Issue by mxa** [sharelatex/web-sharelatex#227]
When using Firefox 46.0a2 (Developer Edition), the PDF which is supposed to be displayed on the right hand side inside the browser is downloaded instead. Works as expected in Chrome though.

**Comment by zeigerpuppy** [comment]
this may be caused by your default settings for processing PDFs in Firefox, also try changing the PDF viewer in the project settings

**Comment by mxa** [comment]
It works now. It could be because either you changed something, Mozilla did changes in one of their updates or it was indeed my settings, but I'm not aware of changing them.
