### ISSUE TITLE
Copy doesn't belong to same folders as original

### ISSUE THREAD

**Issue by javierhonduco** [sharelatex/web-sharelatex#230]
I'm not sure if it's a bug or a feature, but sometimes is a bit annoying and I would say it's not the behavior most users expect.

**Comment by henryoswald** [comment]
Hi,

this is intentional at the moment, however I can see your point. Do other people feel the same?

**Comment by javierhonduco** [comment]
Let's see!
What about a specific setting for that?

BTW. thank you for sharelatex 💞😁
