### ISSUE TITLE
getLoggedInUserId undefined

### ISSUE THREAD

**Issue by HuidaeCho** [sharelatex/web-sharelatex#239]
Hi, I just upgraded from 0.1.4 to 0.2.0 and ran grunt migrate. When I try to access sharelatex, it fails with a server error. The log file says the following:

    TypeError: /home/geni/usr/local/src/sharelatex/web/app/views/layout.jade:65
        63|                     window.systemMessages = !{JSON.stringify(systemMessages).replace(/\//g, '\\/')};
        64|                     window.ab = {};
      > 65|                     window.user_id = '#{getLoggedInUserId()}';
        66|
        67|             - if (typeof(settings.algolia) != "undefined")
        68|                     script.

    undefined is not a function
      at eval (<anonymous>:595:61)
      at eval (<anonymous>:2054:22)

**Comment by henryoswald** [comment]
Hi,

if you go to /logout and log back in again does it work?

**Comment by HuidaeCho** [comment]
Wow! It's real time.. Thanks for the quick reply. No, I'm getting the same error. Maybe, it's because I did "git pull origin master" instead of pulling the 0.2.0 snapshot?

**Comment by HuidaeCho** [comment]
Was that "grunt migrate" really necessary to move up to 0.2.0?

**Comment by henryoswald** [comment]
ah yeah that will really blow things up. You really need to use the docker release ideally. And run the db migrations.

**Comment by HuidaeCho** [comment]
hmm... is there a way to pull 0.2.0 from github directly? Like git tag or something?

**Comment by henryoswald** [comment]
yeah there should be a tag but docker is the correct way to go about it.

**Comment by HuidaeCho** [comment]
yeah, but for some reason, i had to install it manually. please let me know how i can pull 0.2.0 from github. Thanks.

**Comment by henryoswald** [comment]
The git repos will have tags at v0.2.0 but its hard for me to give you direct instructions sorry.

**Comment by HuidaeCho** [comment]
ok. i see the tag. i'll figure out and try again. Thanks!

**Comment by HuidaeCho** [comment]
Perfect! It's working again after checking out v0.2.0. Thanks for the great software!

**Comment by HuidaeCho** [comment]
For those who will face the same issue, I did the following to checkout v0.2.0 and migrate the database:

 git pull origin master
 git checkout tags/v0.2.0
 for i in `ls */.git|grep :|sed 's/.git://'`; do (cd $i; git pull origin master); done
 for i in `ls */.git|grep :|sed 's/.git://'`; do (cd $i; git checkout tags/v0.2.0); done
 grunt migrate

**Comment by hulk1st** [comment]
I think you may just run
```sudo git clone -b release https://github.com/sharelatex/sharelatex.git /var/www/sharelatex``` to get the latest release (v0.2.0 in this case).
