### ISSUE TITLE
Missing clear cache button

### ISSUE THREAD

**Issue by Kyslik** [sharelatex/web-sharelatex#248]
From [documentation](https://www.sharelatex.com/learn/Glossaries#Show_the_glossary_in_the_table_of_contents)
>To compile a document that contains a glossary in ShareLaTeX you don't have to do anything special, but if you add new terms to the glossary once you compiled it, make sure to click on Clear cached files first (drop-down menu next to "Download" button).

But all I see when I click on drop-down menu is
![image](https://cloud.githubusercontent.com/assets/2067589/15507637/b5928eee-21cc-11e6-93c7-2bb12677305e.png)

Am I missing something?

----

Found the clear cache button inside **Logs and output files**.

Can be closed; + documentation should be updated.

**Comment by henryoswald** [comment]
Thanks.
