### ISSUE TITLE
Error on simultaneous compiling

### ISSUE THREAD

**Issue by Stig9999** [sharelatex/web-sharelatex#249]
Sometimes when two people, compile at the same time we get the following error:
Compile Error. Sorry, your LaTeX code couldn't compile for some reason. Please check the errors below for details, or view the raw log.

**Comment by henryoswald** [comment]
This is being fixed at the moment with https://github.com/sharelatex/web-sharelatex/pull/254

**Comment by rdmorin** [comment]
Is this issue still present on the sharelatex servers? I'm getting this error tonight. Haven't seen it before. Not sure what to make of it. I even get it on a simple .tex file that (I think) should always compile:

\documentclass{article}
\usepackage{graphicx}
\begin{document}
\section{Label1}
\label{label1}
This section is referenced by File1.
\end{document}
