### ISSUE TITLE
Website not in root directory 

### ISSUE THREAD

**Issue by mzuenni** [sharelatex/web-sharelatex#256]
Hello i am trying to set up my own sharelatex instance and want it to be acessable via my.domain/sharedlatex/ 
(i am running the web interface in an docker image and proxy it to that location)
the problem is that the site automatically redirects me to my.domain/login and not to my.domain/sharedlatex/login

is there a way to fix this behaviour?

**Comment by henryoswald** [comment]
It is not possible to run ShareLaTeX under a subpath sorry.
