### ISSUE TITLE
CSRF not working

### ISSUE THREAD

**Issue by the-glu** [sharelatex/web-sharelatex#264]
Hello,

I have issues trying to setup the docker image (0.2.0 or the latest).

I have 403 responses when I try to login or reset password.

Logs show that the CSRF token is invalid:

`{"name":"web-sharelatex","hostname":"34c1f93eba77","pid":76,"level":40,"err":{"message":"invalid csrf token","name":"ForbiddenError","stack":"ForbiddenError: invalid csrf token\n  at csrf (/var/www/sharelatex/web/node_modules/csurf/index.js:112:19)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at session (/var/www/sharelatex/web/node_modules/express-session/index.js:398:7)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at cookieParser (/var/www/sharelatex/web/node_modules/cookie-parser/index.js:34:14)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at serveStatic (/var/www/sharelatex/web/node_modules/express/node_modules/serve-static/index.js:74:16)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at Function.handle (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:176:3)\n  at router (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:46:12)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:615:15\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:256:14)\n  at Function.handle (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:176:3)\n  at router (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:46:12)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at /var/www/sharelatex/web/app/js/infrastructure/Server.js:168:14\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at app.use.res.render.title (/var/www/sharelatex/web/app/js/infrastructure/Server.js:158:12)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at module.exports (/var/www/sharelatex/web/app/js/infrastructure/OldAssetProxy.js:27:14)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at module.exports (/var/www/sharelatex/web/app/js/infrastructure/RedirectManager.js:23:14)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at /var/www/sharelatex/web/node_modules/metrics-sharelatex/http.coffee:30:3\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at methodOverride (/var/www/sharelatex/web/node_modules/method-override/index.js:79:5)\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at /var/www/sharelatex/web/node_modules/multer/index.js:218:19\n  at Layer.handle [as handle_request] (/var/www/sharelatex/web/node_modules/express/lib/router/layer.js:95:5)\n  at trim_prefix (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:312:13)\n  at /var/www/sharelatex/web/node_modules/express/lib/router/index.js:280:7\n  at Function.process_params (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:330:12)\n  at next (/var/www/sharelatex/web/node_modules/express/lib/router/index.js:271:10)\n  at /var/www/sharelatex/web/node_modules/body-parser/lib/read.js:129:5\n  at invokeCallback (/var/www/sharelatex/web/node_modules/body-parser/node_modules/raw-body/index.js:262:16)\n  at done (/var/www/sharelatex/web/node_modules/body-parser/node_modules/raw-body/index.js:251:7)\n  at IncomingMessage.onEnd (/var/www/sharelatex/web/node_modules/body-parser/node_modules/raw-body/index.js:307:7)\n  at IncomingMessage.emit (events.js:92:17)\n  at _stream_readable.js:944:16\n  at process._tickDomainCallback (node.js:502:13)\n","code":"EBADCSRFTOKEN"},"url":"/login","method":"POST","msg":"invalid csrf","time":"2016-06-24T13:36:46.314Z","v":0}`

Checking headers, no cookie is set, so I assume this may be the problem, my old sharelatex install set a `sharelatex.sid` cookie.

I'm behing an ssl nginx proxy, configured as said on the wiki. Using direct access don't works either. I also tried direct access into the container on the port 3000, no cookie is set.

I tried to set (or unset) `SHARELATEX_BEHIND_PROXY` and `SHARELATEX_SECURE_COOKIE` but with the same error.

`SHARELATEX_SITE_URL` is set to the external endpoint on the ngnix with ssl.

I tried differents browsers, same error.

Any advice ? Thanks !

**Comment by the-glu** [comment]
Ok, I found my problem.

If I don't set `SHARELATEX_SECURE_COOKIE`, set it to 0, false, False or what ever, it's dosen't works.

But if I edit https://github.com/sharelatex/sharelatex-docker-image/blob/master/settings.coffee#L132 to `secureCookie: false` it's works.

So it's an issue with environment variables in the docker image :)

**Comment by xoxys** [comment]
I had the same error. If you use https and enabled 
```
SHARELATEX_SECURE_COOKIE=true
SHARELATEX_BEHIND_PROXY=true
```
you have to set `proxy_set_header X-Forwarded-Proto $scheme;` in nginx vhost. Otherwise the cookie is not set.
