### ISSUE TITLE
Editor word-wrapping is poor

### ISSUE THREAD

**Issue by jpallen** [sharelatex/web-sharelatex#28]
The editor ( https://github.com/ajaxorg/ace‎ ) word wraps between the end of a word and the full stop, and makes other poor choices. It's clearly set up to be a code editor, but ShareLaTeX is mostly used to write prose. This may or may not be a simple fix in the Ace editor.

**Comment by ELLIOTTCABLE** [comment]
:+1: on this; also see #223 re: disabling soft-wrapping entirely.
