### ISSUE TITLE
Local install has missing pages

### ISSUE THREAD

**Issue by psybers** [sharelatex/web-sharelatex#31]
When visiting the url '/user/subscription' on my local ShareLaTeX install, I get an error page:

```Sorry, we can't find the page you are looking for.```

A similar issue occurs with the templates page '/templates' but may be unrelated (I can file as a separate bug if it is).

Under 'Account -> Subscription' on the top-right of the page.

Also when trying to use things like History or Dropbox (it forwards there).

**Comment by henryoswald** [comment]
You can now set what you want in headings/links via the settings file. Defaults are currently sensible.
