### ISSUE TITLE
Add support for REMOTE_USER (webserver auth)

### ISSUE THREAD

**Issue by klada** [sharelatex/web-sharelatex#311]
I would like my webserver to handle the authentication instead of Sharelatex. This could be Basic Auth in the most trivial case, but would certainly not be limited to this.

It would be nice if Sharelatex could trust the `REMOTE_USER` set by the webserver for such authentication scenarios.

**Comment by jpallen** [comment]
This isn't on our roadmap at the moment, sorry.
