### ISSUE TITLE
Selecting text with tap-and-hold does not work on iOS

### ISSUE THREAD

**Issue by vtsatskin** [sharelatex/web-sharelatex#313]
A common use case in text editing on the iPad is to tap a word and hold to select it or adjacent text. This does not work on iOS which makes working with large blocks of text impossible (e.g. copy, cut, delete).

IOS Version: 9.3.5

**Comment by sampsyo** [comment]
When I try to select text on iOS, text entry stops working altogether. (iOS 10.2.)

**Comment by henryoswald** [comment]
Im going to merge this into https://github.com/sharelatex/web-sharelatex/issues/313

Our mobile/tablet support is not great at the moment. Touch events on the editor are the main issue we are fighting against, it is something we really want to solve in the future though.

**Comment by sampsyo** [comment]
FWIW, @henryoswald, this is #313. Maybe you meant #312?

**Comment by henryoswald** [comment]
Copy paste fail, actually meant https://github.com/sharelatex/web-sharelatex/issues/13

thanks.
