### ISSUE TITLE
vim keybinding :sp (split view)

### ISSUE THREAD

**Issue by khatchad** [sharelatex/web-sharelatex#324]
I would like to see a split view option (:sp for vim).

**Comment by henryoswald** [comment]
Thanks, its unlikely we will ever add this in sorry.

**Comment by khatchad** [comment]
I think that a split view would be useful in general, regardless if it's invoked with :sp.

**Comment by henryoswald** [comment]
yeah it would be but unfortunately we have to keep ShareLaTeX dummy level of simple, people can easily trip up so power users loose a bit of functionality sorry.
