### ISSUE TITLE
Public sharing not functional

### ISSUE THREAD

**Issue by zeigerpuppy** [sharelatex/web-sharelatex#367]
In the current community edition, there is an option to mark a project with "Make Public".
However, when the URL is visited by a third party, they are presented with a login dialogue.

This doesn't seem to be the expected behaviour of making a project public, I'm wondering if I'm missing a setting?

**Comment by loconox** [comment]
I encountering the same issue.

**Comment by loconox** [comment]
I found the solution. You must add the following setting to your config file config/settings.[env].coffee where env is the running environment, default env is development :
```
allowPublicAccess: true 
```
See here : [router.coffee line 49](https://github.com/sharelatex/web-sharelatex/blob/master/app/coffee/router.coffee#L49)

**Comment by casselt** [comment]
If you use docker see my answer in sharelatex/sharelatex-docker-image#66.
