### ISSUE TITLE
biber not working (requires manual install)

### ISSUE THREAD

**Issue by zeigerpuppy** [sharelatex/web-sharelatex#368]
when a docker instance is created, `biber` is not available.

It's fixed by logging into the docker container and installing with
```
apt-get install biber
```

This is probably a package worth having installed by default as it's not obvious that it needs to be added.

**Comment by henryoswald** [comment]
did you do a full tex live install after installing the docker image?

**Comment by zeigerpuppy** [comment]
Yes, it looks like the biber package is not installed with texlive-full

**Comment by dns2utf8** [comment]
any news on this issue?

**Comment by Siedlerchr** [comment]
I recently installed the 2016 version of textlive-full and there it was integrated.

**Comment by xoxys** [comment]
The best way to get a full TexLive environment is to use the installer http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
If you have this up and running you can manage TexLive with `tlmgr`. With the manager its easy to install packages like `tlmgr install biber`

**Comment by dedi0003** [comment]
> when a docker instance is created, `biber` is not available.
> 
> It's fixed by logging into the docker container and installing with
> 
> ```
> apt-get install biber
> ```
> 
> This is probably a package worth having installed by default as it's not obvious that it needs to be added.

Thanks, your solution works for me.

**Comment by zeigerpuppy** [comment]
I agree, it's an essential package, would be good to have by default
