### ISSUE TITLE
[feature] Change code font size (e.g. with Ctrl+Mouse Wheel)

### ISSUE THREAD

**Issue by vargavince91** [sharelatex/web-sharelatex#369]
I would like to be able to change the font size in the left (code) panel, without messing up the layout.

What happens now when I zoom in using either `Ctrl + Mouse Wheel` or `Ctrl + (+/- button)` is that the layout also changes and the icons, buttons may get ugly.

What I would like you to consider is adding the functionality to change font size only in the text editor, either via extra buttons (probably better than hacking with the mouse wheel).

If you don't really understand what I meant, you can see it quickly in the browser

1. Open a LaTeX document
1. Open DevTools, Inspect element.
2. Find the element with class `ace_content` and remove `font-size: 12px` CSS property on the element
3. Find the element with `ace-editor-body ace_editor ace-tm` classes and change the `font-size` with the up and down arrows on your keyboard

If you like the idea, I can make the PR in January, unfortunately I'm superbusy with my thesis now :smiley:

**Comment by henryoswald** [comment]
if you look in the left hand menu of the editor there is an option to set this.

**Comment by vargavince91** [comment]
Ah cool, didn't see it, sorry! :+1:
