### ISSUE TITLE
Ligature in code editor

### ISSUE THREAD

**Issue by ymfa** [sharelatex/web-sharelatex#375]
The code editor is set with the style `text-rendering:  optimizeLegibility`, which enables typographic ligatures. For example, the sequence `fi` is replaced by a ligature character `ﬁ`:
![fi](https://cloud.githubusercontent.com/assets/6981180/20564214/1ec51d5e-b184-11e6-816d-dcac89191ec1.png)

The ligature character seems to occupy the space of only one letter in a monospace font, while actually it is two letters. This makes the cursor inaccurate. If I hit backspace immediately after `fit`, I would have deleted the `f` instead of the `t`!

The problem could be fixed by removing this style, or using a monospace font that does not contain ligatures. My current workaround is to apply a customized stylesheet.

I am using Chrome on Ubuntu 16.04.

**Comment by jpallen** [comment]
We haven't been able to reproduce this, or heard other reports of it, so I'll close this for now.

**Comment by felixwiberg** [comment]
This problem still exists. Using Arch and Firefox.

**Comment by danielkappelle** [comment]
@felixwiberg It turned out to be a problem with the monospace font in Arch. I believe this thread helped me solve the issue: https://bbs.archlinux.org/viewtopic.php?id=238832
