### ISSUE TITLE
Add ldap authorization

### ISSUE THREAD

**Issue by HighwayStar** [sharelatex/web-sharelatex#39]
It will be very usefull feature for private installation in organisation that already has ldap user base. There is node-ldapauth project on github that can be used to implement it.

**Comment by riclmb** [comment]
Hello,
how do I do to obtain a deposit ShareLaTeX also including and directly LDAP feature? how I should organize myself with Git repositories? command git remove ang after git pull ?
thank you in advance. Best Regards

**Comment by phuicy** [comment]
@riclmb 
It worth noticing the LDAP option at the bottom of
https://github.com/sharelatex/web-sharelatex/blob/master/config/settings.defaults.coffee

**Comment by henryoswald** [comment]
closing because it is now available as part of ShareLaTeX server pro

**Comment by ralgozino** [comment]
Any chance of getting LDAP in the on premise version?

**Comment by henryoswald** [comment]
We are going to be keeping it as part of the Pro package, there is only so much we can realistically make free.

**Comment by ralgozino** [comment]
Ok! it is totally understandable and makes sense. Thanks for the fast answer!
Cheers!

**Comment by kemnitzs** [comment]
If you are looking for an example implementation that uses ldapjs in the server component have a look at.

https://github.com/worksasintended/overleaf_ldap
