### ISSUE TITLE
Add wordcounting

### ISSUE THREAD

**Issue by jpallen** [sharelatex/web-sharelatex#4]

**Comment by tommycarstensen** [comment]
Any plans to include word count?

**Comment by jpallen** [comment]
It's on the 'things we would love to have in ShareLaTeX if we had time for everything' list, but it's not on the immediate todo list yet. If someone is keen to add it in for their own use, we'd be happy to discuss what we think is a good approach, and hopefully get it merged back in.

**Comment by tommycarstensen** [comment]
This is good enough for me for now:
find . -name "*.tex" | xargs cat | awk '{for(i=1; i<=NF; i++) {first_char=substr($i,1,1); if(first_char=="%") next; cnt++}} END{print cnt}'
15328

Two online pdf word counters gave me 14,914 and 14,624 respectively. I appreciate this is a difficult bug to solve and other things have higher priority.

**Comment by henryoswald** [comment]
This has now been added in
