### ISSUE TITLE
[feature] Let user choose font of the editor

### ISSUE THREAD

**Issue by vittau** [sharelatex/web-sharelatex#403]
Would be nice if we could write the font name in the menu to use as editor font, like DuckDuckGo does for instance. And should be easy enough, no need to integrate with Google Fonts or anything.

**Comment by camwright** [comment]
This was mentioned in #17. I agree it'd be a nice feature. I'll try to look into implementing it when I have more time.

**Comment by jpallen** [comment]
This isn't something on our roadmap, sorry.
