### ISSUE TITLE
Caret disappears when hitting ESC on auto-complete

### ISSUE THREAD

**Issue by staslev** [sharelatex/web-sharelatex#405]
Steps to reproduce:

1. Type `\` and press `cmd + space`
2. An auto-complete combobox appears
3. Hit `ESC` to close the auto-complete combobox. Oops, no caret in main window, must touch mouse.

**Comment by xoxys** [comment]
Same here. Can you test other browsers to check if only Chrome is affected?

**Comment by staslev** [comment]
Unable to reproduce on Safari.

**Comment by staslev** [comment]
Chrome is by far the [most popular browser](https://en.wikipedia.org/wiki/Usage_share_of_web_browsers) so this usability quirk potentially affects quite a few ShareLatex users.

**Comment by jpallen** [comment]
Sorry, I closed this is a duplicate of https://github.com/sharelatex/web-sharelatex/issues/407 since they seem like the same issue?

**Comment by staslev** [comment]
They may be related.

I was able to confirm both on the latest versions of ShareLatex and Chrome running on MacOS `10.10.5`.
I was unable to reproduce either on the same laptop using Safari.
