### ISSUE TITLE
Hitting ESC while search box is open does not return to document

### ISSUE THREAD

**Issue by staslev** [sharelatex/web-sharelatex#407]
Steps to reproduce:

1. Press `cmd + f` to bring up search
2. Hit `ESC` to exit search
3. Instead of the focus going back to the document, it's nowhere to be found

**Comment by xoxys** [comment]
Does this Problem already exist? Can't reproduce on the current release. For me, hitting `ESC` closes the search box.

**Comment by staslev** [comment]
Yes, this is still happening in the current version (you're using ShareLatex's search box, right?)

I'm using Chrome on Mac, when in split screen mode (project files + editor + pdf preview), with the cursor in the editor section, hitting `cmd + f` brings up the ShareLatex search box, hitting `esc` simply removes the focus from the previously opened search box instead of closing it and moving the focus (and the cursor) back to the editor window.

**Comment by xoxys** [comment]
> you're using ShareLatex's search box, right?
Obviously :)

Can you verify this behavior in an other browser like Firefox? I will test it with Chrome on Linux at home.

**Comment by staslev** [comment]
Interesting...

Just tried to reproduce it in Safari, and couldn't - looks like it's related to Chrome (on Mac?).

**Comment by xoxys** [comment]
Will try it later

**Comment by xoxys** [comment]
With Chromium on Linux it works. Can anybody confirm the issue on MacOS or Windows?

**Comment by jpallen** [comment]
I can't reproduce in Chrome on Mac. Will close as this seems like a minor issue?
