### ISSUE TITLE
Cannot share project with existing users

### ISSUE THREAD

**Issue by ralienpp** [sharelatex/web-sharelatex#412]
Note: I am not sure what the actual procedure should look like, so maybe I am misunderstanding the workflow.

Context:

- There are several users in the system **userA** (the admin) and **userB**
- **userA** created a project and wants to share it with **userB**

Sharelatex tells me that **userB** has not yet accepted the invitation; but if I log on as **userB** I see no pending invitations or anything else that would hint that someone else shared a project with me.

If I go to the project URL directly, while logged on as **userB**, Sharelatex says you have no permission to view this (though **userA** has indicated the email address of **userB** as someone they want to share the project with.)

I also configured the SMTP mailer, assuming maybe the matter is that there is an invitation they have to accept by email, specifically for joining this project - however, no message is received (it is not in spam either).

Other types of emails (e.g. registration invitation) were sent successfully, so I assume this is not an issue with email delivery.

**Comment by MJDiaz89** [comment]
I am encountering the same issue.
