### ISSUE TITLE
bcrypt

### ISSUE THREAD

**Issue by jucajuca** [sharelatex/web-sharelatex#426]
hi,

you might want to change packages.json like so:

"dependencies": {
    "archiver": "0.9.0",
   ....
    "bcrypt": "0.8.3",   -----> **"bcrypt": "0.8.5",** 
    .....

This allows newer npm versions to install the web packages. 

cheers!

**Comment by msimonin** [comment]
Running on ubuntu 16.04, this seems required.

**Comment by jpallen** [comment]
This should be updated now.
