### ISSUE TITLE
Vim mode doesn't work in chrome

### ISSUE THREAD

**Issue by iamquang95** [sharelatex/web-sharelatex#480]
I'm using chrome with vim mode. After pressing `I` to go to insert mode, after editing text, pressing `esc` button doesn't exit insert mode, the cursor becomes unmovable. 
Even in normal mode, the cursor is orange, then click `esc`, the button becomes transparent with only orange border. 
![screen shot 2017-04-07 at 11 56 15 pm](https://cloud.githubusercontent.com/assets/8794293/24810799/d2d3d776-1bed-11e7-9494-f6284c4dac58.png) 
![screen shot 2017-04-07 at 11 56 21 pm](https://cloud.githubusercontent.com/assets/8794293/24810805/d6409944-1bed-11e7-8786-9ac6227c7808.png)

This issue only appear with chrome. (Tested with safari)

**Comment by henrywarhurst** [comment]
I'm also having this issue. Any insights would be greatly appreciated!

**Comment by iamquang95** [comment]
Thank you, it's work.
