### ISSUE TITLE
Column selection should be supported (feature)

### ISSUE THREAD

**Issue by Quenty** [sharelatex/web-sharelatex#482]
Using the middle mouse button, column selection should be supported in ShareLatex as part of the multiple-cursors selection system. This feature is supported in Sublime Text and Atom, and I find myself copying and pasting resources from ShareLatex into these text editors to use this feature.

See: https://www.sublimetext.com/docs/2/column_selection.html

**Comment by jpallen** [comment]
We use the editor at https://github.com/ajaxorg/ace, and a change like this is outside of the scope of development we do at ShareLaTeX, so I'd suggest opening an issue there.
