### ISSUE TITLE
Code folding doesn't recognize "part" or "chapter" environments

### ISSUE THREAD

**Issue by NilsEnevoldsen** [sharelatex/web-sharelatex#487]
Code folding recognizes section and subsection (and, buggily, subsubsection (https://github.com/sharelatex/sharelatex/issues/427)), but not part or chapter.

**Comment by jpallen** [comment]
It would be best to report this at https://github.com/ajaxorg/ace, which is where the code folding code comes from. I've noted down this an issue that we may look at internally too and submit a patch to Ace, but I'll close this issue for now.

**Comment by NilsEnevoldsen** [comment]
The issue at Ace, ajaxorg/ace/issues/3367, has just been fixed.

**Comment by jpallen** [comment]
Great! We've got a few other things outstanding that will be fixed by an Ace upgrade so we're planning this soon.
