### ISSUE TITLE
built-in pdf viewer: crop white margins

### ISSUE THREAD

**Issue by Ansa211** [sharelatex/web-sharelatex#501]
Okular pdfviewer has this feature: crop whitespace at the margins of the pages. 

This would be really useful in the built-in sharelatex viewer because it saves lots of space on the screen when one is looking at a paragraph that goes beyond a page break. It would also make it easier to find the right zoom that fits text width and to center the page to show just the text but not the margins.

A pdf with cropped margins can be produces on a linux command line with the command "pdfcrop".

**Comment by dfelder** [comment]
You could use `END {
    system("pdfcrop output.pdf output.pdf");
}` in your latexmkrc file.

**Comment by Ansa211** [comment]
I tried creating a `latexmkrc` file in the root of the project and add the line you suggest, but it does not seem to have any effect.

**Comment by dfelder** [comment]
Here is an [example](https://www.sharelatex.com/project/59433e620788901873a7f768).

**Comment by Ansa211** [comment]
It turned out that the problem was with the local installation of sharelatex - the package _texlive-extra-utils_ which contains the pdfcrop utility was not installed. I woudn't have realised if you hadn't posted the example, so thanks a lot!

**Comment by jpallen** [comment]
Glad you got it working! I'll close this issue since I don't think we'll be making this part of ShareLaTeX directly.
