### ISSUE TITLE
Enhancement: Comments as part of project source files

### ISSUE THREAD

**Issue by bastianilso** [sharelatex/web-sharelatex#503]
https://github.com/sharelatex/web-sharelatex/issues/8 added a comment system, very nice. However, when downloading the source files of my project, I can't find the comments anywhere among the files. Being able to do so would be beneficial both for backup purposes, lossless interoperability with future latex editors or other tools/devices providing functionality for specific purposes (printing, reviewing, higlighting) beyond sharelatex.

**Comment by jpallen** [comment]
We'd like to do this, but haven't yet figured out a way to put these comments into plain text files, and then be able to keep them in sync with ShareLaTeX. Suggestions are welcome here, but I'll close this issue until we have something more concrete to work with.
