### ISSUE TITLE
auto compile support

### ISSUE THREAD

**Issue by xchuwenbo** [sharelatex/web-sharelatex#526]
Does sharelatex.com has an option that can enable auto compile? It seems annoying to click the recompile button again and again...

**Comment by xoxys** [comment]
There is a shortcut (Ctrl+Enter) to start the compiler. For now i have no idea which action should trigger auto compile. Per time? I think on every key press is too much. Any suggestions?

**Comment by jpallen** [comment]
This isn't an option right now, sorry. We'll likely add this soon, particularly since it is supported by Overleaf (see https://www.sharelatex.com/blog/2017/07/20/sharelatex-joins-overleaf.html). I'll close this issue until we have something more concrete to report.
