### ISSUE TITLE
Spell checker English (American) highlights contractions with smart quotes

### ISSUE THREAD

**Issue by jdleesmiller** [sharelatex/web-sharelatex#577]
### Steps to Reproduce

1. Set language to English (American).
2. Type a word with an apostrophe, such as "wouldn't".

###  Expected Behavior

It is not highlighted by the spellchecker.

### Observed Behavior

![image](https://user-images.githubusercontent.com/160829/29461866-36988276-8425-11e7-8b30-c2563092aeaa.png)

**Comment by jpallen** [comment]
Does this only affect American English?

**Comment by jpallen** [comment]
Ah, this is because it's a 'smart quote', not a usual ASCII apostrophe.

**Comment by jpallen** [comment]
For reference: 
![screen shot 2017-08-18 at 15 59 39](https://user-images.githubusercontent.com/31305/29462054-48b58d9c-842e-11e7-8106-e957161f8669.png)

Offending character: ’

**Comment by jdleesmiller** [comment]
Aha, copy and paste strikes again. (In my defense, this was copy and paste from a Markdown file, so I was not expecting smart quotes!) We probably don't want to encourage use of smart quotes, since LaTeX does not like them. I guess we can just close this.

**Comment by jpallen** [comment]
👍 I'm curious... what would it be nice to not suggest? :)

**Comment by jdleesmiller** [comment]
It will become a blog post soon! I will invite you.
