### ISSUE TITLE
Spell check splits words half way through

### ISSUE THREAD

**Issue by jpallen** [sharelatex/web-sharelatex#58]
For example, the Slovenian word 'povprečje' is split into two words by the č character. At the moment I think we whitelist word characters (i.e. a-zA-Z) and use a special Regex code to match all 'alphanumeric' characters. This works for some accents, but clearly not all. Maybe we should switch to a black list, and only split on characters which are not _, {, }, \, etc.

**Comment by kruczjak** [comment]
Same thing with Polish words, splitted by Polish characters.
For example: 
![selection_028](https://cloud.githubusercontent.com/assets/3147506/6657103/3a8b77ca-cb41-11e4-9390-ec138baa4af6.png)

**Comment by jpallen** [comment]
We need an updated regex that matches these characters as 'word' characters. I failed to find a good solution, but suggestions are welcome from anyone with more experience of this.

**Comment by henryoswald** [comment]
should be fixed now
