### ISSUE TITLE
Web API to get project details?

### ISSUE THREAD

**Issue by javascriptlove** [sharelatex/web-sharelatex#606]
I'm trying to find a way to get a list of files (along with their doc IDs) in a project, as well as to validate of that project actually exists. According to router.coffee there is a `privateApiRouter.get  '/project/:project_id/details'` but it says it is deprecated. I see all kind of actions by doc_id, restore, clone, rename etc., but no way to get details about the project. 
Is there a way? Also would be nice to have a full list of actions with some documentation...

**Comment by javascriptlove** [comment]
Ok for anyone looking into this: the `privateApiRouter` uses the `httpAuthUsers` settings (NOT the regular users), hence default user name is `sharelatex` and password is randomly generated upon docker startup. That is located in `/etc/sharelatex/settings.coffee`. Still there's no API to get list of folders/files in a project..

**Comment by jpallen** [comment]
I'm afraid that all of these APIs are just implemented for our internal services to talk to, rather than designed as a public API. We don't have any plans for a documented and public API at the moment, sorry.
