### ISSUE TITLE
Bug: Unable to upload new files. Buttons gone.

### ISSUE THREAD

**Issue by larsjohan** [sharelatex/web-sharelatex#619]
Tried clicking the "upload" button, the modal appears, but there is nothing in the modal body.
(No button or field for drag-and-drop, as previously).

I've not worked on this project, but maybe it's related to the recent commits regarding "fineuploader"?

As a sidenote, this is on the hosted version at https://www.sharelatex.com/

**Comment by jpallen** [comment]
We have just deployed a fix which will hopefully fix this. Is it working for you now?

**Comment by larsjohan** [comment]
It works perfectly. Thanks!
