### ISSUE TITLE
All of my projects are gone

### ISSUE THREAD

**Issue by ghenshaw** [sharelatex/web-sharelatex#621]
I logged on to my share latex account yesterday morning, Dec 30th, and everything was fine. All of my projects were there. Then, in the evening, I found that all of my projects were gone. All I saw was the message asking me to make my first project. There was nothing in the deleted projects folder and all of the links I sent to my collaborators stopped working (Page Not found).

Please give me advice about what to do.

**Comment by jpallen** [comment]
This was an issue on sharelatex.com. ghenshaw email support as well and we helped them there.
