### ISSUE TITLE
search & replace across multiple files.

### ISSUE THREAD

**Issue by henryoswald** [sharelatex/web-sharelatex#79]
It should be possible to search and replace in all files in a project. This will probably need to be done on the server side which makes it more complex.

**Comment by KChalk** [comment]
I would also *really* appreciate this feature for work on my thesis.

**Comment by tanismar** [comment]
+1. I actually changed from Overleaf to Sharelatex for its much better search tool, but this is quite of a bummer, when looking for double definitions, etc

**Comment by popcorncolonel** [comment]
Please

**Comment by Gronis** [comment]
+1

**Comment by JeffLCoughlin** [comment]
This feature would be very useful. We are paying for a group subscription and have a project with many files --- trying to hunt down errors and re-word things across the project is very difficult without being able to search all files.

**Comment by arthurpaimarnold** [comment]
+1

**Comment by Mikrolous** [comment]
+1

**Comment by compton-scatter** [comment]
+1

**Comment by TobiasPalludan** [comment]
+1

**Comment by apcamargo** [comment]
Why was this issue closed?

**Comment by him229** [comment]
+1

**Comment by Jelstra95** [comment]
+1

**Comment by henryoswald** [comment]
it is something we want todo but don't have capacity todo at the moment.

**Comment by Gronis** [comment]
If this is something you want to do but you don't have the resources to do it, then you should keep the issue open until you have the resources.

**Comment by esguti** [comment]
It would we great to have this feature

**Comment by bjsmith** [comment]
+1. Seems like a really basic piece of editing functionality to have

**Comment by speedstyle** [comment]
+1

**Comment by thiagoald** [comment]
+1

**Comment by davidpomerenke** [comment]
Please reopen! @henryoswald 
The issue has not been addressed, so no reason to close. 
Also, it is like the most important feature missing right now. Can't believe you haven't added this in 5 years!

**Comment by Breus** [comment]
Unfortunate to see this issue closed without any action taken. This feature would have been a nice addition to Overleaf!

**Comment by stevenwdv** [comment]
Please implement this!

**Comment by ferdiamg** [comment]
Really needed. Can't always render out a .pdf to search externally. Really breaking the workflow.

**Comment by gibberblot** [comment]
Very useful when trying to find e.g. text from expanded macros, which aren't where Latex reports them to be.

**Comment by bean5** [comment]
I've been watching this one for years. It had been forgotten. Plus it is marked as closed. Maybe it will be reopened reopened if you @ mention someone still active on the team.

**Comment by davidpomerenke** [comment]
@ShaneKilkelly @jdleesmiller @40thieves @jpallen

**Comment by mcoblenz** [comment]
This is a major hassle; I have to download the whole project, do this operation locally, and then re-upload. Please re-open this important issue and consider it for a future release.

**Comment by haoxuw** [comment]
Congratulations on a fine job listening to your costumers' feedback, looking forward to reply to this thread in 2025.

Jokes aside, it's not me being entitled -- I'm actually paying for an overleaf subscription.

**Comment by mserranom** [comment]
I'm sorry we haven't been more explicit on the reasons to close this ticket. We've basically changed our internal way to track bugfixes, feature requests, etc, which is not open to the public. The best channel to report problems and feedback with overeleaf.com is our contact page: https://www.overleaf.com/contact.

The open source repositories remain open for specific issues of individual Overleaf services (like this one), or general Overleaf Community Edition issues (https://github.com/overleaf/overleaf/issues).

The feature in particular has been, and it's still considered in our roadmap, but we can't confirm a timeframe yet.

**Comment by nikhilweee** [comment]
@mserranom Has there been any progress over the last (six years and) six months that you might want to share with us?

**Comment by cben** [comment]
Would a pull request help?

Can you give any guidance what it'd take technically?
Does the UI even have all files in memory, or only one at a time, loaded/unloaded when you click another file on left pane?

**Comment by jdleesmiller** [comment]
> Does the UI even have all files in memory, or only one at a time

Only one at a time, which is why this is not so easy!

Changes that will bring this feature closer are planned. The ticket is closed, but we have not forgotten.

**Comment by greati** [comment]
A temporary solution (if it is worth the effort) is to use git integration to have the project in a local repository and use VS code to do the replacements (or any text editor with such capability).

**Comment by mcoblenz** [comment]
Unfortunately, Overleaf's GitHub integration requires that I have one paper per repository, which is not the arrangement I have or want.

**Comment by glhrmv** [comment]
Adding my voice to this issue. It's a very basic and expected feature of text editors. One has to wonder if the system architecture was well thought out to begin with considering this is still an issue half a decade later.

**Comment by JanBargeman** [comment]
+1

**Comment by merelanne** [comment]
+1

**Comment by fedhere** [comment]
+1. this is crippling for large projects

**Comment by chriscoey** [comment]
+1

**Comment by mweiss17** [comment]
+1

**Comment by s184186** [comment]
+1

**Comment by j4l-Shvn** [comment]
+1

**Comment by ekosman** [comment]
+1

**Comment by Bha91** [comment]
> I would also _really_ appreciate this feature for work on my thesis.

I can guess you graduated but this feature was not added

**Comment by lstappen** [comment]
+1

**Comment by hvanhaele** [comment]
+1

**Comment by mueller91** [comment]
+1
