### ISSUE TITLE
Provide a comment system for commenting on tex files

### ISSUE THREAD

**Issue by jpallen** [sharelatex/web-sharelatex#8]
Allow users to leave comments and messages for their collaborators within the documents. Coming back to the editor after a while should show you any new comments, and they should probably be hidden once read.

The easiest way to implement this might be to store the comment directly in the .tex file as a tex comment, with some meta data to assign it to a user/timestamp. This would mean there is no issue with keeping the comments up to date when updates come in from Dropbox etc, and would also allow the comments to be accessible offline.

**Comment by ivosluganovic** [comment]
I absolutely agree. Being an extensive user of Google Docs, I immediately fell in love with ShareLatex for the ease of collaboration and syncing.

The only major thing I am missing at the moment is the ability to add comments on the documents in a similar way as it is possible with Google Docs.

**Comment by zeigerpuppy** [comment]
perhaps the existing chat system could be used with some sort of tag that sticks with the doc.  It's a bit tricky to think of the  best way to do this while still keeping the document self contained.  The other way would be to use something like above which inserts a \note{} field in the actual file, this would be better for portability but may break on occasion (eg: the above notes don't like being in captions).  
Personally, I think commenting would go well with a mode that hides or prevents editing of LaTeX commands so that naive users don't inadvertently mess with the code.

**Comment by henryoswald** [comment]
We have had some discussions about this between the team recently. We also decided it is best to put the comments in the latex source. We actually spoke to WriteLaTeX and they have implemented something similar and would be happy to give us their regex so the comments are compatible. 

Integrating these with the chat side bar would be great, it would not be hard to put the data in there from a technical point of view so long as the comments are time stamped.

If someone has time todo this please let me know and I would be happy to work very closely with you, we don't have time to do it for a while.

**Comment by JElchison** [comment]
New to the conversation.  FWIW, I like how [Papeeria](https://www.papeeria.com/auth/demo) handles inline comments.  They're added to the .tex file as comments in a particular format, but rendered by the browser as yellow pop-ups per line.  When out of focus, the comments are collapsed to avoid cluttering the content.

Example:
```tex
% * <A.N.Onym> 15:00:55 07 Dec 2015 UTC-0500:
% comment inline
% ^ <A.N.Onym> 15:01:01 07 Dec 2015 UTC-0500:
% yes!
% ^ <A.N.Onym> 15:01:08 07 Dec 2015 UTC-0500:
% multi
% line
% comment
Normal content here.
```

Note the use of a `%` to indicate a new comment thread, and `^` to indicate a reply.  Comment header includes username, timestamp, and timezone.

I like how this scheme isn't a TeX tag, but rather a simple comment.  (I'm thinking of managers who want to review/comment on documents, but are scared of "coding".)

I agree with the notion of keeping these line-based comments separate from the chat sidebar.  Keeping comment threads contextual is key.

**Comment by JElchison** [comment]
Screenshot of my above commentary on Papeeria:
![untitled](https://cloud.githubusercontent.com/assets/1757771/11638399/c8ca37bc-9cf4-11e5-8a0c-c0cd670f2441.png)

Note the purple placeholder where the comment thread exists.  Also, the yellow float-over to add a new comment on a different line.

**Comment by henryoswald** [comment]
Thanks that is very interesting. If it's super easy getting a shot of the
line 20 uncolapsed would be great. Does it auto hide normally?

On Monday, 7 December 2015, JElchison <notifications@github.com> wrote:

> Screenshot of my above commentary on Papeeria:
> [image: untitled]
> <https://cloud.githubusercontent.com/assets/1757771/11638399/c8ca37bc-9cf4-11e5-8a0c-c0cd670f2441.png>
>
> Note the purple placeholder where the comment thread exists. Also, the
> yellow float-over to add a new comment on a different line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sharelatex/web-sharelatex/issues/8#issuecomment-162646288>
> .
>


-- 
Henry Oswald
shareLaTeX.com co-founder

**Comment by JElchison** [comment]
Hi @henryoswald, the example from [this comment above](https://github.com/sharelatex/web-sharelatex/issues/8#issuecomment-162645273) shows what's collapsed at line 20.

The purple box is hidden normally.  Check out https://www.papeeria.com/auth/demo for a live demo (no signup required).

**Comment by cben** [comment]
Overleaf also renders graphically % comments in a very similar format:
```
First line of comment may be after text. % * <beni.cherniavsky@gmail.com> 2015-04-01T12:35:35.685Z:
%
%  Comment.
%
% ^ <beni.cherniavsky@gmail.com> 2015-04-01T12:37:28.021Z:
%
%  Reply to comment.
%
% ^ <beni.cherniavsky@gmail.com> 2016-03-10T13:42:33.588Z.
```
(the last "closes" the discussion, so it's rendered collapsed.)

Interoperability test:
- Papeeria renders Overleaf's format (different date format is simply shown as is).
  It doesn't recognize the whole discussion if first line % is after some text.
  It doesn't render the closing line ending with `.`
- Overleaf doesn't render Papeeria format.  It probably insists on parsing the timestamp which it renders as e.g. "11 months ago".

Anyway :+1: for ShareLaTeX to adopt same format to help migrating documents with comments between systems.

**Comment by dfelder** [comment]
Perhaps you could place a url to a comment thread, so the document is not cluttered too much when editing offline. This would also prevent people from messing up the format. 
```latex
% Thread: https://sharelatex.com/t/28d95a6e3b85ae
```
On sharelatex the link could be handled in some kind of overlay. Other editors can embed an iframe or be given an api.

**Comment by Ademord** [comment]
This functionality proposal was filed in the drawer?

**Comment by Alex92rus** [comment]
The Ab comment reviewing system was added recently.

**Comment by apskim** [comment]
Could you please add a hotkey for “Add comment”? Perhaps <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>M</kbd>, like in Word and Google Docs.

**Comment by igoralmeida** [comment]
> The Ab comment reviewing system was added recently.

I'm guessing this is what is mentioned in #651. Is there a plan to release the functionality in this repo (or anywhere)?
