### ISSUE TITLE
Autocomplete references and labels

### ISSUE THREAD

**Issue by jpallen** [sharelatex/web-sharelatex#9]
When typing a \cite or \ref command, there should be an autocomplete list of all references or labels available in the document.

This will require storing some metadata in the project, keeping track of the labels and citations in different files. Otherwise, the whole document would need scanned every time which is infeasible for large projects.

**Comment by budde377** [comment]
+1

**Comment by zeigerpuppy** [comment]
+1 
This is a really essential feature when editing complex documents.
It would also allow an outline mode if this data was available

**Comment by Philipp91** [comment]
+1
This metadata could also be used to provide a Strg+click functionality to jump to the definition of a label from the code.
